name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
env:
  APP_NAME: mi-gpt
  DOCKERHUB_REPO: xkrfer/mi-gpt

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate App Version
        run: |
          echo APP_VERSION=${GITHUB_SHA::8} >> $GITHUB_ENV
          echo $APP_VERSION

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: |
            linux/amd64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
